package com.smartdispenser.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val PrimaryLight = Color(0xFF1E88E5)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD6E3FF)
val OnPrimaryContainerLight = Color(0xFF001B3F)
val SecondaryLight = Color(0xFF535F70)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD7E3F7)
val OnSecondaryContainerLight = Color(0xFF101C2B)
val TertiaryLight = Color(0xFF6B5778)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF2DAFF)
val OnTertiaryContainerLight = Color(0xFF251431)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF9F9FF)
val OnBackgroundLight = Color(0xFF1A1C1E)
val SurfaceLight = Color(0xFFF9F9FF)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFE0E2EC)
val OnSurfaceVariantLight = Color(0xFF44474E)
val OutlineLight = Color(0xFF75777F)

// Dark Colors
val PrimaryDark = Color(0xFFA8C8FF)
val OnPrimaryDark = Color(0xFF003063)
val PrimaryContainerDark = Color(0xFF00468B)
val OnPrimaryContainerDark = Color(0xFFD6E3FF)
val SecondaryDark = Color(0xFFBBC7DB)
val OnSecondaryDark = Color(0xFF253141)
val SecondaryContainerDark = Color(0xFF3B4859)
val OnSecondaryContainerDark = Color(0xFFD7E3F7)
val TertiaryDark = Color(0xFFD6BEE4)
val OnTertiaryDark = Color(0xFF3B2948)
val TertiaryContainerDark = Color(0xFF523F60)
val OnTertiaryContainerDark = Color(0xFFF2DAFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF111316)
val OnBackgroundDark = Color(0xFFE2E2E6)
val SurfaceDark = Color(0xFF111316)
val OnSurfaceDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF44474E)
val OnSurfaceVariantDark = Color(0xFFC4C6CF)
val OutlineDark = Color(0xFF8E9099)

// Status Colors
val SuccessLight = Color(0xFF2E7D32)
val SuccessDark = Color(0xFF81C784)
val Error = Color(0xFFD32F2F)